package Calculator;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author anmijurane
 */
public class Processo extends javax.swing.JFrame {

    random acc = new random();   
        
    /**
     * Creates new form Processo
     */
    public Processo() {
        initComponents();  
        //successes();
        GetNumberRigth();
        GetNumberLeft();
        getOperator();
        Operation();
        
    }
    
    
    static int numberRigth2;
    static int numberLeft2;
    static String operator;
    static int result;
    public static int contCorrect = 0;
    public static int contIncorrect = 0;
    static int resultInt;
    static int contador = 1;
    static Result dl = new Result();
    //Arreglos
    static ArrayList<Integer> ArrRight = new ArrayList<Integer>();
    static ArrayList<String> ArrOperator = new ArrayList<String>();
    static ArrayList<Integer> ArrLeft = new ArrayList<Integer>();
    static ArrayList<Integer> ArrResultInter = new ArrayList<Integer>();
    static ArrayList<Integer> ArrResultExt = new ArrayList<Integer>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        FirstValue = new javax.swing.JLabel();
        Operator = new javax.swing.JLabel();
        SecondValue = new javax.swing.JLabel();
        equals = new javax.swing.JLabel();
        result_kid = new javax.swing.JTextField();
        Btn_enviar = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Resuelve la siguiente operación:");

        FirstValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FirstValue.setText("0");

        Operator.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Operator.setText("+/-");

        SecondValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SecondValue.setText("0");

        equals.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        equals.setText("=");

        result_kid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_kidActionPerformed(evt);
            }
        });

        Btn_enviar.setText("Verificar y Siguiente");
        Btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_enviarActionPerformed(evt);
            }
        });

        Siguiente.setText("Resúestas");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Siguiente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(result_kid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Btn_enviar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result_kid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siguiente)
                    .addComponent(Btn_enviar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_enviarActionPerformed
        
        try{
        successes();
        GetNumberRigth();
        GetNumberLeft();
        getOperator();
        Operation();
        result_kid.setText("");
        result_kid.requestFocus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingresa un número.");
        }        
        //System.out.println("Buenas: " +contCorrect);
        //System.out.println("Malas: " +contIncorrect);
        //this.show();
        //this.dispose();  
                
        contador++;
        System.out.println("contador " +contador);
        
        if (contador == 10) {
            dl.show();
            this.dispose();
        }
    }//GEN-LAST:event_Btn_enviarActionPerformed
           
    public void successes(){        
        String kid_result = result_kid.getText();
        resultInt = Integer.parseInt(kid_result);
        ArrResultExt.add(resultInt);
        if (result == resultInt) {
            JOptionPane.showMessageDialog(null, "Correcto");            
            contCorrect++;
        }else if (result != resultInt){
            JOptionPane.showMessageDialog(null, "Incorrecto");
            contIncorrect++;
            //System.out.println("correcto: " +contIncorrect);
        }        
        
        Result set = new Result();
        set.setResult_ext(contCorrect, contIncorrect);
        
        //System.out.println(""+a);
        //System.out.println("Ya no hay mas operaciones");
    }
    
    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        /*        
        Result open = new Result();
        open.show();
        this.dispose();*/
    }//GEN-LAST:event_SiguienteActionPerformed

    private void result_kidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_kidActionPerformed
        
    }//GEN-LAST:event_result_kidActionPerformed

    public void GetNumberRigth(){
        double numberRigth = acc.getRandom(0,9);
        numberRigth2 = acc.ConvrtInteger(numberRigth);
        ArrRight.add(numberRigth2);
        FirstValue.setText(""+numberRigth2);        
    }
    
    public void GetNumberLeft(){        
        double numberLeft = acc.getRandom(0,numberRigth2-1);
        numberLeft2 = acc.ConvrtInteger(numberLeft);
        ArrLeft.add(numberLeft2);
        SecondValue.setText(""+numberLeft2);
        //System.out.println(numberLeft2);    
    }
    
    public void getOperator(){
        operator = acc.Operator();
        ArrOperator.add(operator);
        Operator.setText(operator);
    }
    
    public void Operation(){
        if(operator == "+"){            
            result = numberRigth2 + numberLeft2;            
        }else if(operator == "-"){
            result = numberRigth2 - numberLeft2;
        }        
            //System.out.println(""+result);
            ArrResultInter.add(result);
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_enviar;
    private javax.swing.JLabel FirstValue;
    private javax.swing.JLabel Operator;
    private javax.swing.JLabel SecondValue;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel equals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField result_kid;
    // End of variables declaration//GEN-END:variables
}
